name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cmake -B build
    - run: cmake --build build --config Release
    - uses: actions/upload-artifact@v2.2.0
      with:
        name: mtsd-cli-win64
        path: build/cli/Release/mtsd-cli.exe
