name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cmake --help
    - run: cmake -B build -D CMAKE_BUILD_TYPE=Release
    - run: cmake --build build
    - run: ls build
